cassandra write_failures_test.py::TestWriteFailures::test_mutation_quorum false true
log_dst_dir = /users/masix/vm_images/ZebraConf/app_meta/logs
the_test is write_failures_test.py::TestWriteFailures::test_mutation_quorum
rm: cannot remove '/tmp/my_log.txt': No such file or directory
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /users/masix/dtest/bin/python3
cachedir: .pytest_cache
rootdir: /users/masix/cassandra-dtest, inifile: pytest.ini
plugins: timeout-1.4.2, repeat-0.9.1, flaky-3.7.0
timeout: 1200.0s
timeout method: signal
timeout func_only: False
collecting ... collected 1 item

write_failures_test.py::TestWriteFailures::test_mutation_quorum 
-------------------------------- live log call ---------------------------------
22:40:52,130 cassandra.cluster WARNING Host 127.0.0.3:9042 has been marked down
PASSED                                                                   [100%]
===Flaky Test Report===

test_mutation_quorum passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

========================== 1 passed in 45.71 seconds ===========================
[msx] rc = 0
mv /tmp/my_log.txt /users/masix/vm_images/ZebraConf/app_meta/logs/write_failures_test.py::TestWriteFailures::test_mutation_quorum-output_1643172086122_1200728969.txt
