cassandra transient_replication_ring_test.py::TestTransientReplicationRing::test_move_forwards_between_and_cleanup true true
the_test is transient_replication_ring_test.py::TestTransientReplicationRing::test_move_forwards_between_and_cleanup
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /users/masix/dtest/bin/python
cachedir: .pytest_cache
rootdir: /users/masix/cassandra-dtest, inifile: pytest.ini
plugins: timeout-1.4.2, repeat-0.9.1, flaky-3.7.0
timeout: 900.0s
timeout method: signal
timeout func_only: False
collecting ... collected 1 item

transient_replication_ring_test.py::TestTransientReplicationRing::test_move_forwards_between_and_cleanup 
-------------------------------- live log setup --------------------------------
13:59:19,857 ccmlib.node WARNING [msx] ccmlib:copy_config_files.py, conf_dir = /users/masix/cassandra/conf
13:59:19,944 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node1
13:59:20,16 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node1
13:59:20,110 ccmlib.node WARNING [msx] ccmlib:copy_config_files.py, conf_dir = /users/masix/cassandra/conf
13:59:20,195 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node2
13:59:20,264 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node2
13:59:20,358 ccmlib.node WARNING [msx] ccmlib:copy_config_files.py, conf_dir = /users/masix/cassandra/conf
13:59:20,443 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node3
13:59:20,512 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node3
-------------------------------- live log call ---------------------------------
13:59:40,847 ccmlib.node WARNING [msx] ccmlib:copy_config_files.py, conf_dir = /users/masix/cassandra/conf
13:59:40,943 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node4
13:59:41,18 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node4
14:00:51,571 cassandra.cluster WARNING Host 127.0.0.2:9042 has been marked down
14:00:52,680 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 2.1 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
14:00:54,787 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 3.44 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
14:00:58,298 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 8.4 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
14:01:06,726 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 16.96 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
PASSED                                                                   [100%]
===Flaky Test Report===

test_move_forwards_between_and_cleanup passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

========================== 1 passed in 174.65 seconds ==========================
[msx] rc = 0
